import Button from '@/components/shared/Button';
import Head from 'next/head';
import { InferGetServerSidePropsType } from 'next';
import Link from 'next/link';
import Title from '@/components/shared/Title';
import clientPromise from '../lib/mongodb';
import styled from 'styled-components';

const HomeContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const HomeWrapper = styled.div`
  max-width: 500px;
  width: 100%;
  border: 5px black solid;
  text-align: center;
  padding: 30px;
`;

const ButtonWrapper = styled.div`
  margin: 20px;
`;

export default function Home({ isConnected }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  console.log('isConnected', isConnected);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <HomeWrapper>
          <Title>Interview Prep</Title>
          <ButtonWrapper>
            <Button>Sign In</Button>
          </ButtonWrapper>
          <ButtonWrapper>
            <Link href="/main/guest">
              <Button>Guest</Button>
            </Link>
          </ButtonWrapper>
        </HomeWrapper>
      </HomeContainer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await clientPromise;
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
    //
    // `const client = await clientPromise`
    // `const db = client.db("myDatabase")`
    //
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands

    return {
      props: { isConnected: true },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
}
